### ISSUE TITLE
Pré-requis, installation, configuration et utilisation

### ISSUE THREAD

**Issue by ColinMaudry** [adebeo/adopteunpanneau2#1]
Bonjour,

Pourriez-vous s'il vous plaît ajouter quelques informations supplémentaires sur le fonctionnement de votre application ?

- pré-requis (quelle version de Ruby ?), framework ? Bibliothèques ?
- comment l'installer
- comment la configuer
- comment la démarrer

Il est possible qu'elle fasse l'objet d'un déploiement plus large au sein du collectif #MAVOIX.

Merci :+1:

**Comment by denisadebeo** [comment]
bjr, ;-)

Mon point de vue est que le plus simple est de faire pointer le sous
domaine sur mon instance heroku:

   - Ca prend 5 minutes,
   - ca marche pendant 2 mois, puis on repasse en gratuit
   - ca coute 60€ pour la pleine puissance, ( qu'on met sur les compte de
   campagen de Lyon , je suis mandataire financier, ca sera plus simple)
   - 0 maintenance
   - mise à jour poussée en une minute ( par exemple pour ajouter d'autre
   circonscription)

Sinon ci -dessous la réponse à tes questions.

>
>    - pré-requis (quelle version de Ruby ?), framework ? Bibliothèques ?
>
> ruby 2.26
rails
postgres

>
>    - comment l'installer
>
> Sur linux uniquement
Installer rvm pour s'assurer d'avoir ruby 2.26
Installer postgres
puis

   1. mettre un nginx ou un apache
   2. telecharger le git
   3. dans le dossier du git
   4. faire pointer le nginx ou le apache vers le dossier public
   5. régler le fichier database.yml
   6. bundle install
   7. rake routes
   8. rake db:create
   9. rake db:migrate
   10. rake db:seed
   11. ajouter un certificat de securité sur le serveur ( nécéssaire pour
   la geolocalisation)
   12. ajouter un hook sur le git pour faciliter les mises à jour
   13. boire un coup parce que la journée a été longue et la route difficile


>    - comment la configuer
>
> RAS

>
>    - comment la démarrer
>
> rails s

Très cordialement


---------------------------------------------
Denis Bolomier
Sketchup Hero
www.adebeo.com
denis@adebeo.com
--------------------------------------------

**Comment by adebeo** [comment]
Sinon, il y aura peut être un wiki pur l'installation fait par la france insoumise ? 
https://arcane-wave-90582.herokuapp.com/panneaus
:-)

**Comment by denisadebeo** [comment]
voir le fork de la France insoumise:
https://github.com/baptwit/adopteunpanneau2/wiki
