### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by cypriengay** [adebeo/adopteunpanneau2#10]
Bonjour ! Actuellement, lorsqu'on tente de modifier l'état d'un panneau, ça répond : 
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
Merci d'avance !

**Comment by denisadebeo** [comment]
merci du test je regarde ce soir

Très cordialement


---------------------------------------------
Denis Bolomier
Sketchup Hero
www.adebeo.com
denis@adebeo.com
--------------------------------------------

2017-05-23 12:38 GMT+02:00 Cyprien Gay <notifications@github.com>:

**Comment by cypriengay** [comment]
Merci ! (Note : ça fonctionnait très bien encore ce matin vers 9h). Et bravo !!!

**Comment by denisadebeo** [comment]
bon oui mais tout lemonde demande des modifs

Très cordialement


---------------------------------------------
Denis Bolomier
Sketchup Hero
www.adebeo.com
denis@adebeo.com
--------------------------------------------

2017-05-23 12:42 GMT+02:00 Cyprien Gay <notifications@github.com>:

**Comment by denisadebeo** [comment]
juste une question something went worng, , c'est avant que tu arrive sur la
page de modi ou lorsque tu les valide ?

Très cordialement


---------------------------------------------
Denis Bolomier
Sketchup Hero
www.adebeo.com
denis@adebeo.com
--------------------------------------------

**Comment by cypriengay** [comment]
C'est avant de voir le formulaire pour modifier le panneau. Autrement dit, c'est juste après avoir cliqué sur le rectangle orange ou rouge dans la page qui liste les panneaux de la circonscription (Paris-2, arrondissements 5 6 7).
OS=Ubuntu, Nav=Firefox. Idem avec smartphone sous firefoxOS.

**Comment by denisadebeo** [comment]
Bonjour, j'ai mis à jour le site adopte un panneau:
-> ajout de marseille 4 ieme circo
-> sur les cartes une punaise montre ou l'utilisateur est
-> la liste des panneaux est séparée des cartes
-> si on ajoute '&editable' à la fin des urls de listes permet de:
 -> d'ajouter des panneaux
         -> de supprimer des panneaux
         -> par exemple: 'https://adopteunpanneau.herokuapp.com/panneaus?ville=13_%20Bouches-du-Rh%C3%B4ne_%2014%20CIRCO&editable=true'
