### ISSUE TITLE
[Non bloquant] div:modal après modification panneau

### ISSUE THREAD

**Issue by cypriengay** [adebeo/adopteunpanneau2#11]
Ceci est non bloquant.
Quand je valide la modification d'un panneau, le moulinet mouline.
Du coup, je dois fermer la page ou revenir en arrière pour retrouver la liste des panneaux.
(C'est sans doute le div:modal d'après la discussion sur une autre issue, je n'ai pas vérifié).

**Comment by denisadebeo** [comment]
Bonjour, j'ai mis à jour le site adopte un panneau:
-> ajout de marseille 4 ieme circo
-> sur les cartes une punaise montre ou l'utilisateur est
-> la liste des panneaux est séparée des cartes
-> si on ajoute '&editable' à la fin des urls de listes permet de:
 -> d'ajouter des panneaux
         -> de supprimer des panneaux
         -> par exemple: 'https://adopteunpanneau.herokuapp.com/panneaus?ville=13_%20Bouches-du-Rh%C3%B4ne_%2014%20CIRCO&editable=true'
