### ISSUE TITLE
GeoJSON - MaVoix44

### ISSUE THREAD

**Issue by olivM** [adebeo/adopteunpanneau2#2]
Voici l'emplacement des panneaux pour 2ème circonscription de Loire-Atlantique : 
https://gist.github.com/olivM/a5c311b768660951a2dd704aecad8ec3

**Comment by denisadebeo** [comment]
Je le met n place ce week end.

Envoyé de mon iPhone

**Comment by denisadebeo** [comment]
Done avec 2-3 autres modifs ( peut être bug ) 
https://adopteunpanneau.herokuapp.com/panneaus?ville=Loire-Atlantique_2
