### ISSUE TITLE
Manque la carte

### ISSUE THREAD

**Issue by ghost** [adebeo/adopteunpanneau2#3]
Sur Firefox 53.0.2 la carte n'apparait pas si je change de circo. Elle ne s'affiche que sur la première circo que j'ouvre.

Solution : ouvrir le site dans un nouvel onglet pour pouvoir afficher la carte d'une autre circo.

**Comment by denisadebeo** [comment]
Les liens s ouvrent désormais dans un nouvel onglet.

Le problème semble hyper complexe. Je passe sur Google map des que possible.


Envoyé de mon iPhone

**Comment by denisadebeo** [comment]
normalement l'ouevrture dans un nouvelle onglet doit marché désormais
