### ISSUE TITLE
Première ligne étrange

### ISSUE THREAD

**Issue by ghost** [adebeo/adopteunpanneau2#4]
Pour la première circo de la liste (69 Rhône), la première ligne du tableau est "space" : 
voir sur la carte 	2017-05-15 19:12:58 UTC                            A recoller

Problème dans un fichier d'import ???

**Comment by denisadebeo** [comment]
Bjr,

oui il doit s'agir d'un probleme d'import, il faudrait me donner le bon nom

Très cordialement


---------------------------------------------
Denis Bolomier
Sketchup Hero
www.adebeo.com
denis@adebeo.com
--------------------------------------------
