### ISSUE TITLE
Nouveaux panneaux

### ISSUE THREAD

**Issue by Lorenzolelynx** [adebeo/adopteunpanneau2#5]
Bonsoir, 

simple petite question est-il possible d'ajouter une nouvelle circo dans l'appli ou est-ce trop tard?

Merci

Laurent

**Comment by denisadebeo** [comment]
non aucun pb

Très cordialement


---------------------------------------------
Denis Bolomier
Sketchup Hero
www.adebeo.com
denis@adebeo.com
--------------------------------------------

**Comment by Lorenzolelynx** [comment]
Ok et quelle est la demarche? Je ne m'y connais pas trop en code source et ce genre de choses ;-)

Merciiiii

**Comment by denisadebeo** [comment]
Il faudrait m'indiquer la circo d'abord, pour regarder ce qu'il existe.
Soit je l'ai en stock soit il faudra la saisir


Très cordialement


---------------------------------------------
Denis Bolomier
Sketchup Hero
www.adebeo.com
denis@adebeo.com
--------------------------------------------

2017-05-17 19:03 GMT+02:00 Lorenzolelynx <notifications@github.com>:

**Comment by Lorenzolelynx** [comment]
Merci pour la réponse!

Il s'agit de Strasbourg 1

Bonne nuit

Laurent

**Comment by denisadebeo** [comment]
J'ai toutes les circos du bas-rhin sauf la première

Normalement le candidat a du récupérer la listedes bureau de vote,.

Il faudrait la transformer en excel avec l'adresse precise de chaque bureau
de vote

Très cordialement


---------------------------------------------
Denis Bolomier
Sketchup Hero
www.adebeo.com
denis@adebeo.com
--------------------------------------------

**Comment by Lorenzolelynx** [comment]
Parfait, effectivement la liste est prête avec les adresses!

C'est très sympathique de l'ajouter merci!

Bonne soirée

[PASSAGES Panneaux2.xlsx](https://github.com/adebeo/adopteunpanneau2/files/1012388/PASSAGES.Panneaux2.xlsx)

**Comment by Lorenzolelynx** [comment]
#

**Comment by denisadebeo** [comment]
done !

**Comment by Lorenzolelynx** [comment]
Merci pour l'ajout de la circo!
Bonne journée
Laurent

      De : adebeo <notifications@github.com>
 À : adebeo/adopteunpanneau2 <adopteunpanneau2@noreply.github.com> 
Cc : Lorenzolelynx <Malibucoco1664@yahoo.fr>; State change <state_change@noreply.github.com>
 Envoyé le : Vendredi 19 mai 2017 8h30
 Objet : Re: [adebeo/adopteunpanneau2] Nouveaux panneaux (#5)
   
Closed #5.—

**Comment by Lorenzolelynx** [comment]
La page ne fait que se charger et ne s'affiche pas. Ceci est le cas chez moi pour d'autres circonscriptions aussi est ce un problème général?

**Comment by denisadebeo** [comment]
@Lorenzolelynx tu peut vérifier à nouveau ?
https://adopteunpanneau.herokuapp.com/panneaus_gm?ville=67_%20Bas-Rhin_%20Alsace%20_%2001%20CIRCO

**Comment by denisadebeo** [comment]
@Lorenzolelynx 
Il faut bien vérifier que tu as activé la géolocalisation sur ton téléphone.
Merci d'avance.
Sinon, indique moi ton telephone, le navigateur que tu utilises, ...
