### ISSUE TITLE
Impossible d'intéragir avec les panneaux sans géolocalisation

### ISSUE THREAD

**Issue by ColinMaudry** [adebeo/adopteunpanneau2#8]
Actuellement, si pour une raison ou une autre mon appareil (ordinateur, téléphone) n'est pas géolocalisé, je ne peux pas éditer l'état des panneaux de ma circonscription.

Le div.modal et loading.gif empêchent toute interaction.

Serait-il possible de rendre la géolocalisation optionnelle pour l'édition de l'état des panneaux, de façon à pouvoir gérer ses panneaux plus facilement ?

**Comment by denisadebeo** [comment]
Salut, j'aime bien l'idée qu'il faille être à coté du panneau pour
interagir ? C'est le cahier des charge de l'atelier qui m'avait été
transmis par l'atelier qui avait eu l'idée.

Je vois pas pourquoi, quelqu'un qui n'est pas a coté d'un panneau pour jugé
de son état.

Si tu insiste, je peux faire une page "secrete" qui permettent d'éditée les
status?

Très cordialement


---------------------------------------------
Denis Bolomier
Sketchup Hero
www.adebeo.com
denis@adebeo.com
--------------------------------------------

**Comment by ColinMaudry** [comment]
Cela limite l'utilisation aux personnes qui ont un smartphone, mais garantit en parallèle une certaine qualité. Soit.

Serait-il possible, faute de pouvoir interagir, de pouvoir au moins consulter la position et le statut des panneaux sans géolocalisation ?

**Comment by denisadebeo** [comment]
Ok je regarde.



Envoyé de mon iPhone

**Comment by denisadebeo** [comment]
@ColinMaudry, désormais j'affiche les panneaux et j'enlève les bouton. Sans geoloc. 
J'ai peur que ton probleme viennent d'ailleurs car normalement meme en wifi tu as acces à la geoloc.

Peut tu tester ? quelles est ta config ? quelle ville regardes tu ?

**Comment by ColinMaudry** [comment]
Je suis connecté en Ethernet et je regarde la 8ème circonscription d'Ille et Vilaine (35).

**Comment by denisadebeo** [comment]
@ColinMaudry, Ca ne marche toujours pas ? normalement j'ai fait un truc pour que cela marche même sans geoloc. Tu peux confirmer ou infirmer ( si ca ne marche pas, quelle navigateur, quel OS)

**Comment by ColinMaudry** [comment]
- ça marche sous Firefox / Linux Mint
- ça ne marche pas sous Firefox / Android 5.1 (sans les Google Services) = j'ai toujours le modal qui bloque tout. J'ai cleané le cache, même résultat.

**Comment by denisadebeo** [comment]
C est donc plus un bug que autre chose.

Encore une question si tu veux bien.

Si tu remplace dans l URL ´panneaus_gm' par ´panneaus' ( tu peux n'élève le _gm)
ça marche ou pas sur Android ?

Par exemple:

https://adopteunpanneau.herokuapp.com/panneaus?ville=44-Loire-Atlantique-Pays-de-la-Loire-02-CIRCO


Envoyé de mon iPhone

**Comment by ColinMaudry** [comment]
Toujours pas. Pour l'instant je vais utiliser notre carte Google maps : https://www.google.com/maps/d/viewer?mid=1nbY0O-SbvFuojaSezE6gnrT29So&ll=48.104545627569074%2C-1.6690229963035108&z=15

**Comment by Lorenzolelynx** [comment]
Bonjour,

Ca ne fonctionne toujours pas sur iOS ;-)

Merci

Laurent

**Comment by denisadebeo** [comment]
Salut ça marche sur mon iPhone 6s.

Est tu sur d avoir activer ta geolocalisation ? Sur le téléphone et le navigateur ?

Quand tu dis ça marche pas , que ce passe t il exactement? 
Quelle circo ?

Envoyé de mon iPhone

**Comment by Lorenzolelynx** [comment]
Merciii j'avais dû répondre non machinalement lors de la demande d'activation de la géo localisation ;-)

Bonne journée 

Laurent

**Comment by denisadebeo** [comment]
Cool ca marche alors @Lorenzolelynx

**Comment by Lorenzolelynx** [comment]
;-) 

Laurent

**Comment by ColinMaudry** [comment]
Je suis de nouveau bloqué par le div.modal sous Firefox / Mint. Obligé de supprimer la class "loading" du body pour pouvoir éditer les panneaux.

Pourrais-tu faire en sorte que **quelle que soit la situation**, le loading ne bloque pas tout ? Par exemple en mettant juste le gif dans un coin ?

Mais s'il te plaît, enlève ce div.modal :slightly_smiling_face:

**Comment by denisadebeo** [comment]
done
