### ISSUE TITLE
Possibilité d'éditer nom et position des panneaux

### ISSUE THREAD

**Issue by ColinMaudry** [adebeo/adopteunpanneau2#9]
Les données chargées pour 35-8 ne sont pas à jour.

Certains panneaux n'existent plus, d'autres ont été créés.

Serait-il possible de pouvoir éditer le nom et la position (lat/long) des panneaux ?

**Comment by denisadebeo** [comment]
J'ai ajoutée une liste ou l'utilisateur peu tout editer ( confiance , confiance)

**Comment by denisadebeo** [comment]
le model est sur 20%
